### ISSUE TITLE
Pulling docker image "janeliascicomp/solr-search" failed

### ISSUE THREAD

**Issue by dinglufe** [JaneliaSciComp/jacs-cm#1]
I'm setting up a development environment according to document "docs/ComposeDeployment.md". When running command `./manage.sh up none --dbonly -d` (in the Initialize Databases step), it prompt that the docker image `janeliascicomp/solr-search` is required, but we didn't find it on [dockerhub](https://hub.docker.com/u/janeliascicomp).

BTW, pulling image `jacs-init-1.0.6` also failed. There is only v1.0.2.

**Comment by krokicki** [comment]
Thanks for the feedback. The code in master is a work in progress, and currently you should use the v1.0 tag of this repo for a stable deployment. I'll make that clear in the docs. 

But you may want to hold off a few days. We're very close to a 2.0 release, and should have it ready this week.
