### ISSUE TITLE
No such image error while running jacs-cm-8.6

### ISSUE THREAD

**Issue by pmadhanbabu** [JaneliaSciComp/jacs-cm#11]
Experiencing "No such image error" while running jacs-cm-8.6 for the below services:

**jacs_solr:**
p50yzz7cdknjsd9qjcvfdma9k jacs_solr.1 janeliascicomp/solr-search:1.0.2@sha256:b74842b5d7c224f4ecb20e6c28bdca625749c246c656c4200f81fbca610a2a4a biowkst Shutdown Rejected 36 minutes ago "No such image: janeliascicomp/solr-search:1.0.2@sha256:b74842b5d7c224f4ecb20e6c28bdca625749c246c656c4200f81fbca610a2a4a"

**jacs_jade-agent3**
dlc0kcktcv173tg4ilfe4jrxb jacs_jade-agent3.1 janeliascicomp/jacs-storage:1.14.3@sha256:68392d2bfba4a0d93dc0cfa8240a5927998f90fddfe2ef98f8246b3b4ec14074 bioimg Shutdown Rejected 35 minutes ago "No such image: janeliascicomp/jacs-storage:1.14.3@sha256:68392d2bfba4a0d93dc0cfa8240a5927998f90fddfe2ef98f8246b3b4ec14074"

**jacs_jacs-messaging**
pytvpwt67axis992vqr09db8x jacs_jacs-messaging.1 janeliascicomp/jacs-messaging:2.4.11@sha256:4324c8e9485374aba438088e0bf9d4875486dcb09931a51123f1292299da073e biowkst Shutdown Rejected 34 minutes ago "No such image: janeliascicomp/jacs-messaging:2.4.11@sha256:4324c8e9485374aba438088e0bf9d4875486dcb09931a51123f1292299da073e"

**Comment by cgoina** [comment]
All the images are available on dockerhub. What happens when you do `docker pull janeliascicomp/jacs-messaging:2.4.11`?

**Comment by pmadhanbabu** [comment]
Executing the command: docker pull janeliascicomp/jacs-messaging:2.4.11 doesn't have issues. But when executed using the script (./manage.sh start prod) has these issues. Any workarounds?

**Comment by pmadhanbabu** [comment]
Cristian, I remember we had a similar issue for jacs-init (even though the image did exist in docker hub), some time back. Later the issue was resolved when you did publish the latest jacs-init to docker hub

**Comment by cgoina** [comment]
I republished the three problematic containers. Please give it a try and let us know if it works or not

**Comment by cgoina** [comment]
The problem was because there was not enough space on the machine to actually load the latest image
