### ISSUE TITLE
bring up all of the application containers with branch fixes-8.1.1

### ISSUE THREAD

**Issue by freshpomelo** [JaneliaSciComp/jacs-cm#3]
Hi all,

When I ran "./manage.sh compose up standalone -d" for bringing up all of the application containers, it threw an error below:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/10544528/65056441-6cd05500-d9a3-11e9-8852-424ca1076990.png">

What should I do with this error?
Any advices could be greatly appreciated.

**Comment by freshpomelo** [comment]
I comment these code below in the file "jacs-cm/deployments/jacs/docker-compose-app.yml"
106   #jacs-dashboard:
107     # Nginx must run as root
108     #image: ${NAMESPACE}/jacs-dashboard:latest
109     #expose:
110     #  - "8080"
111     #restart: unless-stopped
112     #networks:
113     #  - jacs-net

I don't know whether I did the right option or not.

**Comment by krokicki** [comment]
Yes, that's a good workaround for now. We're currently working on fixing this, by externalizing the jacs-dashboard config. It will work in the next release (8.4).
