### ISSUE TITLE
"Initialize Databases" seems failed 

### ISSUE THREAD

**Issue by freshpomelo** [JaneliaSciComp/jacs-cm#4]
When I tried to run the "Initialize Databases" procedure: ./manage.sh init-databases, the command returned the error below:
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/10544528/65148632-3225f580-da53-11e9-81e6-dcab48d7b167.png">
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/10544528/65148694-4ec22d80-da53-11e9-9fa8-ab5f20aaf484.png">
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/10544528/65148725-5b468600-da53-11e9-82b0-d9940e89a9ba.png">

When I configured the system in the .env.config file, I did only the minimal changes following the instruction.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/10544528/65148862-92b53280-da53-11e9-9aa4-3e8db26240f6.png">

About mongoDB, mysql and rabbitMQ in .env.config file, based on my own understanding from the doc instruction, they should have been deployed in these docker images. Am I right?

What should I do with these tools?
Any advice will be greatly appreciated.

**Comment by freshpomelo** [comment]
I notice that in the ComposeDeployment.md, it said that:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/10544528/65150264-5c2ce700-da56-11e9-8ca5-dbb0a1fc26a4.png">
I'll try to umcomment the mysql and mongodb config in the docker-compose-db.yml
<img width="918" alt="image" src="https://user-images.githubusercontent.com/10544528/65150339-867ea480-da56-11e9-8baa-8350fb8e00fe.png">

**Comment by freshpomelo** [comment]
I wonder if this message has any potential issue or not?
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/10544528/65154553-46bbbb00-da5e-11e9-9ced-5799c70bd736.png">

**Comment by krokicki** [comment]
I think you've figured it out. The "unable to reach primary" message is harmless, it just takes a while for the Mongo cluster to form.
